// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static EscapeMobility.Controllers.AllProductsController AllProducts = new EscapeMobility.Controllers.T4MVC_AllProductsController();
    public static EscapeMobility.Controllers.EducationController Education = new EscapeMobility.Controllers.T4MVC_EducationController();
    public static EscapeMobility.Controllers.EmergencyServicesController EmergencyServices = new EscapeMobility.Controllers.T4MVC_EmergencyServicesController();
    public static EscapeMobility.Controllers.HealthCareController HealthCare = new EscapeMobility.Controllers.T4MVC_HealthCareController();
    public static EscapeMobility.Controllers.HomeController Home = new EscapeMobility.Controllers.T4MVC_HomeController();
    public static EscapeMobility.Controllers.IndustryController Industry = new EscapeMobility.Controllers.T4MVC_IndustryController();
    public static EscapeMobility.Controllers.InformationController Information = new EscapeMobility.Controllers.T4MVC_InformationController();
    public static EscapeMobility.Controllers.OfficeBuildingsController OfficeBuildings = new EscapeMobility.Controllers.T4MVC_OfficeBuildingsController();
    public static EscapeMobility.Controllers.ProductsAdminController ProductsAdmin = new EscapeMobility.Controllers.T4MVC_ProductsAdminController();
    public static EscapeMobility.Controllers.QuoteController Quote = new EscapeMobility.Controllers.T4MVC_QuoteController();
    public static EscapeMobility.Controllers.ServiceController Service = new EscapeMobility.Controllers.T4MVC_ServiceController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string ada_county_JPG = Url("ada_county.JPG");
            public static readonly string additional_backrest_jpg = Url("additional-backrest.jpg");
            public static readonly string Akademie_der_Kunste_Berlin_jpg = Url("Akademie-der-Kunste-Berlin.jpg");
            public static readonly string Alabel_products_scheef_10graden_png = Url("Alabel_products-scheef-10graden.png");
            public static readonly string all_products_jpg = Url("all-products.jpg");
            public static readonly string armrests_jpg = Url("armrests.jpg");
            public static readonly string arrowDownWhite_png = Url("arrowDownWhite.png");
            public static readonly string az_alma2_jpg = Url("az-alma2.jpg");
            public static readonly string azmlogo_2_png = Url("azmlogo_2.png");
            public static readonly string beeldmerk_png = Url("beeldmerk.png");
            public static readonly string berufsfoerderungswerk_jpg = Url("berufsfoerderungswerk.jpg");
            public static readonly string beurs3_jpg = Url("beurs3.jpg");
            public static readonly string blockButtonBg_png = Url("blockButtonBg.png");
            public static readonly string blocksBg_png = Url("blocksBg.png");
            public static readonly string bodyBg_png = Url("bodyBg.png");
            public static readonly string breadcrumbSpacer_png = Url("breadcrumbSpacer.png");
            public static readonly string cbbb_badge_horz_png = Url("cbbb-badge-horz.png");
            public static readonly string cbBorderBg_png = Url("cbBorderBg.png");
            public static readonly string Contact_foto_Marlie_png = Url("Contact_foto_Marlie.png");
            public static readonly string contentBg_png = Url("contentBg.png");
            public static readonly string contentFooterBg_png = Url("contentFooterBg.png");
            public static readonly string ContentListLiBg_png = Url("ContentListLiBg.png");
            public static readonly string DhrvanLeeuwen_jpg = Url("DhrvanLeeuwen.jpg");
            public static readonly string distribiteurs_vrij225h_png = Url("distribiteurs_vrij225h.png");
            public static readonly string distributors_wanted_jpg = Url("distributors-wanted.jpg");
            public static readonly string dust_cover_standard_standard_alu_jpg = Url("dust-cover-standard-standard-alu.jpg");
            public static readonly string education_jpg = Url("education.jpg");
            public static readonly string emergency_food_rations__mainstay_1200_energy_bar__1_package_jpg = Url("emergency-food-rations--mainstay-1200-energy-bar--1-package.jpg");
            public static readonly string emergency_food_rations__mainstay_2400__1_package_jpg = Url("emergency-food-rations--mainstay-2400--1-package.jpg");
            public static readonly string emergency_food_rations__mainstay_3600__1_package_jpg = Url("emergency-food-rations--mainstay-3600--1-package.jpg");
            public static readonly string emergency_services_jpg = Url("emergency-services.jpg");
            public static readonly string emergency_water_rations_jpg = Url("emergency-water-rations.jpg");
            public static readonly string escape_alarm_jpg = Url("escape-alarm.jpg");
            public static readonly string escape_carry_chair_standard_with_extra_package_jpg = Url("escape-carry-chair-standard-with-extra-package.jpg");
            public static readonly string escape_carry_chair_standard_jpg = Url("escape-carry-chair-standard.jpg");
            public static readonly string escape_carry_chair_standardplus_jpg = Url("escape-carry-chair-standardplus.jpg");
            public static readonly string escape_carry_chair_xs_jpg = Url("escape-carry-chair-xs.jpg");
            public static readonly string Escape_Carry_Chair_png = Url("Escape-Carry-Chair.png");
            public static readonly string escape_chair_comfort_jpg = Url("escape-chair-comfort.jpg");
            public static readonly string escape_chair_standard_alu_with_extra_package_jpg = Url("escape-chair-standard-alu-with-extra-package.jpg");
            public static readonly string escape_chair_standard_alu_jpg = Url("escape-chair-standard-alu.jpg");
            public static readonly string escape_chair_standard_jpg = Url("escape-chair-standard.jpg");
            public static readonly string escape_chair_standardplus_jpg = Url("escape-chair-standardplus.jpg");
            public static readonly string escape_chair_standardalu_jpg = Url("escape-chair_standardalu.jpg");
            public static readonly string Escape_Chair2_png = Url("Escape-Chair2.png");
            public static readonly string escape_harness_including_accessory_bag_jpg = Url("escape-harness-including-accessory-bag.jpg");
            public static readonly string escape_locker_jpg = Url("escape-locker.jpg");
            public static readonly string escape_mattress_compact_jpg = Url("escape-mattress-compact.jpg");
            public static readonly string escape_mattress_fold_jpg = Url("escape-mattress-fold.jpg");
            public static readonly string escape_mattress_healthcare_jpg = Url("escape-mattress-healthcare.jpg");
            public static readonly string escape_mattress_solo_jpg = Url("escape-mattress-solo.jpg");
            public static readonly string escape_mattress_storage_bag_jpg = Url("escape-mattress-storage-bag.jpg");
            public static readonly string escape_mattress_stretcher_black_jpg = Url("escape-mattress-stretcher-black.jpg");
            public static readonly string Escape_Mattress_png = Url("Escape-Mattress.png");
            public static readonly string escape_mobility_company_usa_1016457_png = Url("escape-mobility-company-usa-1016457.png");
            public static readonly string escape_point_locker_jpg = Url("escape-point-locker.jpg");
            public static readonly string escape_smokehood_single_pack__smoke_mask_jpg = Url("escape-smokehood-single-pack--smoke-mask.jpg");
            public static readonly string escape_smokehood_soft_pack__smoke_mask_jpg = Url("escape-smokehood-soft-pack--smoke-mask.jpg");
            public static readonly string escape_smokehood_traveller_pack__smoke_mask_jpg = Url("escape-smokehood-traveller-pack--smoke-mask.jpg");
            public static readonly string escape_smokehood_twin_pack__smoke_mask_jpg = Url("escape-smokehood-twin-pack--smoke-mask.jpg");
            public static readonly string escapechair_comfort150_png = Url("escapechair_comfort150.png");
            public static readonly string EscapeChairLiveBoard_slide1_jpg = Url("EscapeChairLiveBoard_slide1.jpg");
            public static readonly string FEMA_jpg = Url("FEMA.jpg");
            public static readonly string fixation_headrest_jpg = Url("fixation-headrest.jpg");
            public static readonly string footerGlow_png = Url("footerGlow.png");
            public static readonly string footerListstyle_png = Url("footerListstyle.png");
            public static readonly string footerTitles_en_png = Url("footerTitles_en.png");
            public static readonly string footrest_jpg = Url("footrest.jpg");
            public static readonly string footstrap_for_footrest_jpg = Url("footstrap-for-footrest.jpg");
            public static readonly string galena_park_jpg = Url("galena park.jpg");
            public static readonly string gebouw_autosNEW600_web_jpg = Url("gebouw_autosNEW600-web.jpg");
            public static readonly string greenArrow_png = Url("greenArrow.png");
            public static readonly string healthcare_jpg = Url("healthcare.jpg");
            public static readonly string ievac_smoke_fire_hood_ebp_900_jpg = Url("ievac-smoke-fire-hood-ebp-900.jpg");
            public static readonly string industry_jpg = Url("industry.jpg");
            public static readonly string jvg_logo_jpg = Url("jvg-logo.jpg");
            public static readonly string kennecott_JPG = Url("kennecott.JPG");
            public static readonly string kisco_senior_living_virginia_beach__virginia_jpg = Url("kisco senior living virginia beach, virginia.jpg");
            public static readonly string klantenservice_png = Url("klantenservice.png");
            public static readonly string lebenhsilfe_blau_png = Url("lebenhsilfe-blau.png");
            public static readonly string leftMenuUlBg_png = Url("leftMenuUlBg.png");
            public static readonly string leftMenuUlBottomBg_png = Url("leftMenuUlBottomBg.png");
            public static readonly string leftMenuUlLiBg_png = Url("leftMenuUlLiBg.png");
            public static readonly string leftMenuUlLinkBg_png = Url("leftMenuUlLinkBg.png");
            public static readonly string legstrap_jpg = Url("legstrap.jpg");
            public static readonly string lift_carry_chair_png = Url("lift-carry-chair.png");
            public static readonly string lift_chair_png = Url("lift-chair.png");
            public static readonly string lift_trap_vloer_png = Url("lift-trap-vloer.png");
            public static readonly string liveboard_png = Url("liveboard.png");
            public static readonly string liveboard_nav_png = Url("liveboard_nav.png");
            public static readonly string loader_gif = Url("loader.gif");
            public static readonly string logo_CE_ISO_TUV_png = Url("logo_CE_ISO_TUV.png");
            public static readonly string logo_en_png = Url("logo_en.png");
            public static readonly string mainContentBg_png = Url("mainContentBg.png");
            public static readonly string mainNavLiBg_png = Url("mainNavLiBg.png");
            public static readonly string mainNavLiFirstBg_png = Url("mainNavLiFirstBg.png");
            public static readonly string megafoon_png = Url("megafoon.png");
            public static readonly string modified_footrest_for_the_escape_carry_chair_jpg = Url("modified-footrest-for-the-escape-carry-chair.jpg");
            public static readonly string newsItemBg_png = Url("newsItemBg.png");
            public static readonly string nixall_cleanser__2oz_single_jpg = Url("nixall-cleanser--2oz-single.jpg");
            public static readonly string nixall_disinfectant__quart_bottle_single_jpg = Url("nixall-disinfectant--quart-bottle-single.jpg");
            public static readonly string nixall_vet_response__8oz_single_jpg = Url("nixall-vet-response--8oz-single.jpg");
            public static readonly string nixall_wound__skin_solution__2oz_single_jpg = Url("nixall-wound--skin-solution--2oz-single.jpg");
            public static readonly string office_buildings_jpg = Url("office-buildings.jpg");
            public static readonly string one_size_fits_all_jpg = Url("one-size-fits-all.jpg");
            public static readonly string padded_seat_jpg = Url("padded-seat.jpg");
            public static readonly string palmetto_JPG = Url("palmetto.JPG");
            public static readonly string paypal_here_logo_1x_png = Url("paypal-here-logo-1x.png");
            public static readonly string phone_png = Url("phone.png");
            public static readonly string productie_jpg = Url("productie.jpg");
            public static readonly string productie_large_jpg = Url("productie_large.jpg");
            public static readonly string products_jpg = Url("products.jpg");
            public static readonly string radio_unchecked_png = Url("radio_unchecked.png");
            public static readonly string RK_logo3_jpg = Url("RK-logo3.jpg");
            public static readonly string scape_cbrn30_jpg = Url("scape-cbrn30.jpg");
            public static readonly string scape_co_cbrn__escape_respirator_jpg = Url("scape-co-cbrn--escape-respirator.jpg");
            public static readonly string seal_for_1016457_png = Url("seal-for-1016457.png");
            public static readonly string search_png = Url("search.png");
            public static readonly string searchButton_png = Url("searchButton.png");
            public static readonly string searchIcon_png = Url("searchIcon.png");
            public static readonly string secure_payment_jpg = Url("secure-payment.jpg");
            public static readonly string secure90x72_gif = Url("secure90x72.gif");
            public static readonly string sliderTitles_png = Url("sliderTitles.png");
            public static readonly string stand_alone_holder_color_black_jpg = Url("stand-alone-holder-color-black.jpg");
            public static readonly string stempel_madeineurope_175_20graden_png = Url("stempel_madeineurope_175-20graden.png");
            public static readonly string subFooterArrow_png = Url("subFooterArrow.png");
            public static readonly string subFooterDivider_png = Url("subFooterDivider.png");
            public static readonly string subFooterIcon_png = Url("subFooterIcon.png");
            public static readonly string subFooterIconHover_png = Url("subFooterIconHover.png");
            public static readonly string topDivider_png = Url("topDivider.png");
            public static readonly string topGlow_png = Url("topGlow.png");
            public static readonly string topLanguages_png = Url("topLanguages.png");
            public static readonly string topPhoneNumber_png = Url("topPhoneNumber.png");
            public static readonly string tweetBg_png = Url("tweetBg.png");
            public static readonly string UK_brochure_Escape_Chair_jpg = Url("UK-brochure-Escape-Chair.jpg");
            public static readonly string UK_brochure_Liggend_Evacueren_jpg = Url("UK-brochure-Liggend-Evacueren.jpg");
            public static readonly string umcgkort_fc_jpg = Url("umcgkort_fc.jpg");
            public static readonly string united_states_attorney_s_office_boston__ma_jpg = Url("united states attorney’s office boston, ma.jpg");
            public static readonly string united_states_marine_corps___mccs_cherry_point__north_carolina_jpg = Url("united states marine corps – mccs cherry point, north carolina.jpg");
            public static readonly string vanbreda2_jpg = Url("vanbreda2.jpg");
            public static readonly string VGR_logo2_jpg = Url("VGR-logo2.jpg");
            public static readonly string wallace_community__1__JPG = Url("wallace_community (1).JPG");
            public static readonly string wallace_community_jpg = Url("wallace_community.jpg");
            public static readonly string youtube_watermark_vflHX6b6E_png = Url("youtube_watermark-vflHX6b6E.png");
            public static readonly string yulius_jpg = Url("yulius.jpg");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class styles {
            private const string URLPATH = "~/Content/styles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class app {
                private const string URLPATH = "~/Content/styles/app";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string basket_1015101831_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/basket.1015101831.min.css") ? Url("basket.1015101831.min.css") : Url("basket.1015101831.css");
                     
                public static readonly string branchepage_0227102118_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/branchepage.0227102118.min.css") ? Url("branchepage.0227102118.min.css") : Url("branchepage.0227102118.css");
                     
                public static readonly string homepage_0227102118_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/homepage.0227102118.min.css") ? Url("homepage.0227102118.min.css") : Url("homepage.0227102118.css");
                     
                public static readonly string jquery_fancybox_1_3_4_0219160601_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fancybox-1.3.4.0219160601.min.css") ? Url("jquery.fancybox-1.3.4.0219160601.min.css") : Url("jquery.fancybox-1.3.4.0219160601.css");
                     
                public static readonly string masterpage_1015101830_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/masterpage.1015101830.min.css") ? Url("masterpage.1015101830.min.css") : Url("masterpage.1015101830.css");
                     
                public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
                     
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class lib {
                private const string URLPATH = "~/Content/styles/lib";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class bootstrap {
                    private const string URLPATH = "~/Content/styles/lib/bootstrap";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string alerts_less = Url("alerts.less");
                    public static readonly string badges_less = Url("badges.less");
                    public static readonly string bootstrap_less = Url("bootstrap.less");
                    public static readonly string breadcrumbs_less = Url("breadcrumbs.less");
                    public static readonly string button_groups_less = Url("button-groups.less");
                    public static readonly string buttons_less = Url("buttons.less");
                    public static readonly string carousel_less = Url("carousel.less");
                    public static readonly string close_less = Url("close.less");
                    public static readonly string code_less = Url("code.less");
                    public static readonly string component_animations_less = Url("component-animations.less");
                    public static readonly string dropdowns_less = Url("dropdowns.less");
                    public static readonly string forms_less = Url("forms.less");
                    public static readonly string glyphicons_less = Url("glyphicons.less");
                    public static readonly string grid_less = Url("grid.less");
                    public static readonly string input_groups_less = Url("input-groups.less");
                    public static readonly string jumbotron_less = Url("jumbotron.less");
                    public static readonly string labels_less = Url("labels.less");
                    public static readonly string list_group_less = Url("list-group.less");
                    public static readonly string media_less = Url("media.less");
                    public static readonly string mixins_less = Url("mixins.less");
                    public static readonly string modals_less = Url("modals.less");
                    public static readonly string navbar_less = Url("navbar.less");
                    public static readonly string navs_less = Url("navs.less");
                    public static readonly string normalize_less = Url("normalize.less");
                    public static readonly string pager_less = Url("pager.less");
                    public static readonly string pagination_less = Url("pagination.less");
                    public static readonly string panels_less = Url("panels.less");
                    public static readonly string popovers_less = Url("popovers.less");
                    public static readonly string print_less = Url("print.less");
                    public static readonly string progress_bars_less = Url("progress-bars.less");
                    public static readonly string responsive_utilities_less = Url("responsive-utilities.less");
                    public static readonly string scaffolding_less = Url("scaffolding.less");
                    public static readonly string tables_less = Url("tables.less");
                    public static readonly string theme_less = Url("theme.less");
                    public static readonly string thumbnails_less = Url("thumbnails.less");
                    public static readonly string tooltip_less = Url("tooltip.less");
                    public static readonly string type_less = Url("type.less");
                    public static readonly string utilities_less = Url("utilities.less");
                    public static readonly string variables_less = Url("variables.less");
                    public static readonly string wells_less = Url("wells.less");
                }
            
                public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
                     
                public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
                public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
                public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
                     
                public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
                public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class fonts {
                    private const string URLPATH = "~/Content/styles/lib/fonts";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
                    public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
                    public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
                    public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
                }
            
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


