// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace EscapeMobility.Controllers
{
    public partial class EmergencyServicesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmergencyServicesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EmergencyServicesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EmergencyServicesController Actions { get { return MVC.EmergencyServices; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "EmergencyServices";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "EmergencyServices";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string EscapeChair = "EscapeChair";
            public readonly string EscapeCarryChair = "EscapeCarryChair";
            public readonly string EscpaeMattress = "EscpaeMattress";
            public readonly string Accessories = "Accessories";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string EscapeChair = "EscapeChair";
            public const string EscapeCarryChair = "EscapeCarryChair";
            public const string EscpaeMattress = "EscpaeMattress";
            public const string Accessories = "Accessories";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Accessories = "Accessories";
                public readonly string EscapeCarryChair = "EscapeCarryChair";
                public readonly string EscapeChair = "EscapeChair";
                public readonly string EscpaeMattress = "EscpaeMattress";
                public readonly string Index = "Index";
            }
            public readonly string Accessories = "~/Views/EmergencyServices/Accessories.cshtml";
            public readonly string EscapeCarryChair = "~/Views/EmergencyServices/EscapeCarryChair.cshtml";
            public readonly string EscapeChair = "~/Views/EmergencyServices/EscapeChair.cshtml";
            public readonly string EscpaeMattress = "~/Views/EmergencyServices/EscpaeMattress.cshtml";
            public readonly string Index = "~/Views/EmergencyServices/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EmergencyServicesController : EscapeMobility.Controllers.EmergencyServicesController
    {
        public T4MVC_EmergencyServicesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EscapeChairOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EscapeChair()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EscapeChair);
            EscapeChairOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EscapeCarryChairOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EscapeCarryChair()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EscapeCarryChair);
            EscapeCarryChairOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EscpaeMattressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EscpaeMattress()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EscpaeMattress);
            EscpaeMattressOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AccessoriesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Accessories()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Accessories);
            AccessoriesOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
