// <auto-generated />
namespace Escape.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MoreChangesToProductSpecifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreChangesToProductSpecifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201411042323406_MoreChangesToProductSpecifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
